name: Node.js
on:
  push:
    branches: ["main"]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: |
          npm install
          npm run clean
          npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  build-example:
    name: Build Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: |
          npm install
          npm run build-example
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist/

  deploy-example:
    name: Deploy Example
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-example
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
